<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SosLan</AssemblyName>
    <RootNamespace>SosLan</RootNamespace>
    <StartupObject>SosLan.App</StartupObject>
    <ApplicationIcon>cloche.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="cloche.ico" LogicalName="SosLan.cloche.ico" />
  </ItemGroup>

</Project>
