<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SosLan</AssemblyName>
    <RootNamespace>SosLan</RootNamespace>
    <ApplicationIcon>cloche.ico</ApplicationIcon>
    <Version>1.0.20</Version>
    <Product>SOS-LAN</Product>
    <Copyright>© Tomline Prod&amp;Co</Copyright>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="cloche.ico" LogicalName="SosLan.cloche.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.12" />
    <PackageReference Include="Velopack" Version="1.2.158" />
  </ItemGroup>

</Project>
